2018-09-18 15:56:51,164 ERROR: Exception on /receptskanner/karl@salmi.se [GET] [in /Users/KarlSalmi/Desktop/Pythonappar/Test1/Bergsal.se/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/KarlSalmi/Desktop/Pythonappar/Test1/Bergsal.se/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/KarlSalmi/Desktop/Pythonappar/Test1/Bergsal.se/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/KarlSalmi/Desktop/Pythonappar/Test1/Bergsal.se/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/KarlSalmi/Desktop/Pythonappar/Test1/Bergsal.se/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/KarlSalmi/Desktop/Pythonappar/Test1/Bergsal.se/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/KarlSalmi/Desktop/Pythonappar/Test1/Bergsal.se/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/KarlSalmi/Desktop/Pythonappar/Test1/Bergsal.se/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
TypeError: recipe() got an unexpected keyword argument 'username'
2018-09-18 15:57:40,645 INFO: Microblog startup [in /Users/KarlSalmi/Desktop/Pythonappar/Test1/Bergsal.se/app/__init__.py:49]
2018-09-18 15:57:44,319 ERROR: Exception on /receptskanner/karl@salmi.se [GET] [in /Users/KarlSalmi/Desktop/Pythonappar/Test1/Bergsal.se/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/KarlSalmi/Desktop/Pythonappar/Test1/Bergsal.se/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/KarlSalmi/Desktop/Pythonappar/Test1/Bergsal.se/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/KarlSalmi/Desktop/Pythonappar/Test1/Bergsal.se/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/KarlSalmi/Desktop/Pythonappar/Test1/Bergsal.se/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/KarlSalmi/Desktop/Pythonappar/Test1/Bergsal.se/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/KarlSalmi/Desktop/Pythonappar/Test1/Bergsal.se/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/KarlSalmi/Desktop/Pythonappar/Test1/Bergsal.se/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
TypeError: recipe() got an unexpected keyword argument 'username'
2018-09-18 15:58:49,110 INFO: Microblog startup [in /Users/KarlSalmi/Desktop/Pythonappar/Test1/Bergsal.se/app/__init__.py:49]
2018-09-18 16:00:58,785 INFO: Microblog startup [in /Users/KarlSalmi/Desktop/Pythonappar/Test1/Bergsal.se/app/__init__.py:49]
2018-09-18 16:01:40,611 INFO: Microblog startup [in /Users/KarlSalmi/Desktop/Pythonappar/Test1/Bergsal.se/app/__init__.py:49]
2018-09-18 16:04:02,673 INFO: Microblog startup [in /Users/KarlSalmi/Desktop/Pythonappar/Test1/Bergsal.se/app/__init__.py:49]
2018-09-18 16:05:37,219 INFO: Microblog startup [in /Users/KarlSalmi/Desktop/Pythonappar/Test1/Bergsal.se/app/__init__.py:49]
2018-09-18 22:20:50,352 INFO: Microblog startup [in /Users/KarlSalmi/Desktop/Pythonappar/Test1/Bergsal.se/app/__init__.py:49]
